package database

// metacriticScoreDB is a comprehensive database of Switch game Metacritic scores.
// Key = title substring (case-insensitive match), Value = metascore (0-100).
// Sourced from Metacritic, OpenCritic, and public review aggregators.
// Games without entries here either have no Metacritic page or too few reviews.
func metacriticScoreDB() map[string]int {
	return map[string]int{
		// ═══ Nintendo EPD / First-Party ═══
		"The Legend of Zelda: Breath of the Wild":         97,
		"The Legend of Zelda: Tears of the Kingdom":       96,
		"The Legend of Zelda: Link's Awakening":           87,
		"The Legend of Zelda: Skyward Sword HD":           81,
		"The Legend of Zelda: Echoes of Wisdom":           86,
		"Super Mario Odyssey":                             97,
		"Super Mario Bros. Wonder":                        92,
		"Super Mario 3D World + Bowser's Fury":            89,
		"Super Mario 3D All-Stars":                        82,
		"New Super Mario Bros. U Deluxe":                  80,
		"Mario Kart 8 Deluxe":                             92,
		"Mario Kart Live: Home Circuit":                   72,
		"Super Smash Bros. Ultimate":                      93,
		"Animal Crossing: New Horizons":                   90,
		"Splatoon 3":                                      83,
		"Splatoon 2":                                      83,
		"Super Mario Maker 2":                             88,
		"Super Mario Party":                               76,
		"Super Mario Party Jamboree":                      76,
		"Mario Party Superstars":                          79,
		"Mario Strikers: Battle League":                   73,
		"Mario Tennis Aces":                               75,
		"Mario Golf: Super Rush":                          70,
		"Nintendo Switch Sports":                          72,
		"Arms":                                            77,
		"1-2-Switch":                                      58,
		"Everybody 1-2-Switch":                            56,
		"Ring Fit Adventure":                              83,
		"Clubhouse Games":                                 82,
		"Big Brain Academy":                               71,
		"Game Builder Garage":                             77,
		"Labo":                                            68,
		"Endless Ocean Luminous":                          58,

		// ═══ Kirby ═══
		"Kirby and the Forgotten Land":                    85,
		"Kirby's Return to Dream Land Deluxe":             80,
		"Kirby Star Allies":                               73,
		"Kirby Fighters 2":                                65,
		"Kirby's Dream Buffet":                            61,

		// ═══ Pokemon ═══
		"Pokemon Scarlet":                      72,
		"Pokemon Violet":                       72,
		"Pokemon Legends: Arceus":              83,
		"Pokemon Sword":                        80,
		"Pokemon Shield":                       80,
		"Pokemon Brilliant Diamond":            73,
		"Pokemon Shining Pearl":                73,
		"Pokemon Let's Go, Pikachu":            79,
		"Pokemon Let's Go, Eevee":              79,
		"New Pokemon Snap":                     79,
		"Pokemon Mystery Dungeon":              68,
		"Pokken Tournament DX":                 80,
		"Detective Pikachu Returns":            69,

		// ═══ Fire Emblem ═══
		"Fire Emblem Engage":                   80,
		"Fire Emblem: Three Houses":            89,
		"Fire Emblem Warriors":                 74,
		"Fire Emblem Warriors: Three Hopes":    80,
		"Tokyo Mirage Sessions":                69,

		// ═══ Xenoblade ═══
		"Xenoblade Chronicles 3":               89,
		"Xenoblade Chronicles 2":               83,
		"Xenoblade Chronicles: Definitive":     89,
		"Xenoblade Chronicles 2: Torna":        80,

		// ═══ Metroid ═══
		"Metroid Dread":                        88,
		"Metroid Prime Remastered":             94,
		"Metroid Prime 4":                      85,

		// ═══ Pikmin ═══
		"Pikmin 4":                             87,
		"Pikmin 3 Deluxe":                      85,
		"Pikmin 1+2":                           79,

		// ═══ Bayonetta ═══
		"Bayonetta 3":                          86,
		"Bayonetta 2":                          84,
		"Bayonetta Origins":                    82,
		"Bayonetta":                            80,

		// ═══ Other Nintendo Published ═══
		"Luigi's Mansion 3":                    86,
		"Luigi's Mansion 2 HD":                 77,
		"Donkey Kong Country: Tropical Freeze": 86,
		"Yoshi's Crafted World":                79,
		"Captain Toad: Treasure Tracker":        81,
		"Paper Mario: The Origami King":        80,
		"WarioWare: Get It Together":           76,
		"WarioWare: Move It":                   74,
		"Astral Chain":                         87,
		"Hyrule Warriors: Age of Calamity":     78,
		"Hyrule Warriors: Definitive":          74,
		"Marvel Ultimate Alliance 3":           73,
		"Daemon X Machina":                     69,
		"Snipperclips":                         80,
		"BoxBoy + BoxGirl":                     80,
		"Part Time UFO":                        78,
		"Good Job":                             78,
		"The Stretchers":                       75,

		// ═══ Square Enix ═══
		"Dragon Quest XI S":                    91,
		"Octopath Traveler":                    83,
		"Octopath Traveler II":                 86,
		"Triangle Strategy":                    83,
		"Bravely Default II":                   76,
		"Live A Live":                          81,
		"NieR: Automata":                       89,
		"Final Fantasy VII":                    82,
		"Final Fantasy VIII":                   78,
		"Final Fantasy IX":                     84,
		"Final Fantasy X":                      81,
		"Final Fantasy XII":                    85,
		"Kingdom Hearts":                       80,
		"Kingdom Hearts: Melody of Memory":     74,
		"Crisis Core: Final Fantasy VII":       77,
		"Harvestella":                          69,
		"Various Daylife":                      54,
		"The DioField Chronicle":               61,
		"Voice of Cards":                       72,
		"Dungeon Encounters":                   66,
		"Chocobo GP":                           64,
		"Chocobo's Mystery Dungeon":            65,

		// ═══ Atlus / SEGA ═══
		"Persona 5 Royal":                      94,
		"Persona 5 Strikers":                   81,
		"Persona 5 Tactica":                    74,
		"Persona 4 Golden":                     87,
		"Persona 3 Portable":                   81,
		"Shin Megami Tensei V":                 84,
		"Shin Megami Tensei III":               73,
		"Unicorn Overlord":                     89,
		"13 Sentinels: Aegis Rim":              90,
		"Catherine: Full Body":                 80,
		"Sonic Frontiers":                      71,
		"Sonic Mania":                          86,
		"Sonic Forces":                         57,
		"Sonic Colors: Ultimate":               66,
		"Sonic Origins":                        72,
		"Super Monkey Ball Banana Mania":       77,
		"Super Monkey Ball Banana Rumble":      72,
		"Puyo Puyo Tetris":                     81,
		"Puyo Puyo Tetris 2":                   75,

		// ═══ Capcom ═══
		"Monster Hunter Rise":                  88,
		"Monster Hunter Stories 2":             81,
		"Monster Hunter Generations Ultimate":  80,
		"Resident Evil 4":                      85,
		"Resident Evil Village":                84,
		"Resident Evil Revelations":            75,
		"Resident Evil Revelations 2":          72,
		"Resident Evil 5":                      73,
		"Resident Evil 6":                      68,
		"Resident Evil 0":                      72,
		"Resident Evil":                        66,
		"Devil May Cry 3":                      82,
		"Devil May Cry":                        75,
		"Devil May Cry 2":                      62,
		"Mega Man 11":                          79,
		"Mega Man Legacy Collection":           76,
		"Mega Man X Legacy Collection":         76,
		"Mega Man Zero/ZX Legacy":              82,
		"Ghosts 'n Goblins Resurrection":       76,
		"Okami HD":                             81,
		"Street Fighter 30th Anniversary":      81,
		"Phoenix Wright: Ace Attorney Trilogy": 82,
		"The Great Ace Attorney Chronicles":    86,
		"Apollo Justice: Ace Attorney Trilogy": 81,

		// ═══ Bandai Namco ═══
		"Tekken 7":                             82,
		"Soulcalibur VI":                       79,
		"Tales of Vesperia":                    79,
		"Tales of Symphonia Remastered":        68,
		"Ni no Kuni":                           82,
		"Ni no Kuni II":                        78,
		"Dragon Ball FighterZ":                 84,
		"Dragon Ball Xenoverse 2":              73,
		"Dragon Ball Z: Kakarot":               72,
		"Naruto Shippuden: Ultimate Ninja Storm":76,
		"JoJo's Bizarre Adventure":             67,

		// ═══ Koei Tecmo ═══
		"Atelier Ryza":                         78,
		"Atelier Ryza 2":                       75,
		"Atelier Ryza 3":                       76,
		"Atelier Sophie 2":                     78,
		"Nioh":                                 81,
		"Fatal Frame: Maiden of Black Water":   63,
		"Fatal Frame: Mask of the Lunar":       68,

		// ═══ Ubisoft ═══
		"Mario + Rabbids Kingdom Battle":       85,
		"Mario + Rabbids Sparks of Hope":       86,
		"Assassin's Creed: The Ezio Collection":71,
		"Assassin's Creed III":                 67,
		"Assassin's Creed: The Rebel Collection":75,
		"Immortals Fenyx Rising":               75,
		"Rayman Legends":                       87,
		"Just Dance 2023":                      72,
		"Just Dance 2024":                      70,
		"Prince of Persia: The Lost Crown":     85,

		// ═══ Bethesda ═══
		"The Elder Scrolls V: Skyrim":          84,
		"DOOM":                                 85,
		"DOOM Eternal":                         80,
		"Wolfenstein II":                       81,
		"Wolfenstein: Youngblood":              66,
		"Quake":                                81,
		"Quake II":                             84,

		// ═══ CD Projekt / 2K / WB ═══
		"The Witcher 3: Wild Hunt":             85,
		"BioShock: The Collection":             80,
		"Borderlands Legendary Collection":     78,
		"XCOM 2 Collection":                    81,
		"Civilization VI":                      75,
		"Diablo III: Eternal Collection":       83,
		"Diablo II: Resurrected":               77,
		"Overwatch":                            73,
		"Crash Bandicoot N. Sane Trilogy":      78,
		"Crash Team Racing Nitro-Fueled":       80,
		"Spyro Reignited Trilogy":              79,
		"Tony Hawk's Pro Skater":               85,
		"LEGO City Undercover":                 69,
		"LEGO Star Wars: The Skywalker Saga":   72,
		"Mortal Kombat 11":                     76,
		"Batman: Arkham Trilogy":               70,
		"Hogwarts Legacy":                      71,

		// ═══ Major Third-Party ═══
		"Dark Souls Remastered":                84,
		"Dark Souls II":                        73,
		"Divinity: Original Sin II":            93,
		"Divinity: Original Sin":               84,
		"Baldur's Gate":                        77,
		"Planescape: Torment":                  80,
		"Neverwinter Nights":                   72,
		"Disco Elysium":                        89,
		"Outer Wilds":                          85,
		"Subnautica":                           81,
		"Subnautica: Below Zero":              77,
		"No Man's Sky":                         81,
		"Life is Strange: True Colors":         78,
		"Life is Strange Remastered":           73,
		"What Remains of Edith Finch":          85,
		"Kentucky Route Zero":                  83,
		"Return of the Obra Dinn":              88,
		"Spiritfarer":                          84,
		"Doki Doki Literature Club Plus":       77,
		"Disney Dreamlight Valley":             68,
		"Among Us":                             79,
		"Fall Guys":                            64,
		"Fortnite":                             75,
		"Rocket League":                        86,
		"Apex Legends":                         73,
		"Warframe":                             76,
		"Palia":                                68,
		"Sky: Children of the Light":           76,

		// ═══ Major Indie ═══
		"Hades":                                93,
		"Hollow Knight":                        90,
		"Celeste":                              92,
		"Stardew Valley":                       89,
		"Dead Cells":                           89,
		"Undertale":                            92,
		"Cuphead":                              86,
		"Ori and the Blind Forest":             89,
		"Ori and the Will of the Wisps":        93,
		"Shovel Knight":                        86,
		"Into the Breach":                      89,
		"Slay the Spire":                       89,
		"Balatro":                              90,
		"Vampire Survivors":                    87,
		"Sea of Stars":                         88,
		"Chained Echoes":                       90,
		"Tunic":                                87,
		"Eastward":                             78,
		"A Short Hike":                         88,
		"Untitled Goose Game":                  79,
		"The Messenger":                        85,
		"CrossCode":                            85,
		"Hyper Light Drifter":                  80,
		"Bastion":                              84,
		"Transistor":                           84,
		"Inside":                               87,
		"Limbo":                                84,
		"Little Nightmares":                    79,
		"Little Nightmares II":                 79,
		"Cult of the Lamb":                     82,
		"Citizen Sleeper":                      84,
		"OlliOlli World":                       87,
		"TMNT: Shredder's Revenge":            85,
		"Streets of Rage 4":                    86,
		"Shantae and the Seven Sirens":         83,
		"Shantae: Half-Genie Hero":             78,
		"SteamWorld Dig 2":                     88,
		"SteamWorld Heist":                     83,
		"SteamWorld Quest":                     76,
		"SteamWorld Build":                     72,
		"Golf Story":                           78,
		"Sports Story":                          62,
		"Owlboy":                               80,
		"Iconoclasts":                          83,
		"Axiom Verge":                          82,
		"Axiom Verge 2":                        78,
		"Blasphemous":                          77,
		"Blasphemous 2":                        79,
		"Guacamelee":                           84,
		"Guacamelee 2":                         83,
		"Katana Zero":                          83,
		"Hotline Miami":                        81,
		"Hotline Miami 2":                      75,
		"Enter the Gungeon":                    82,
		"The Binding of Isaac":                 85,
		"Risk of Rain 2":                       79,
		"Risk of Rain Returns":                 80,
		"Mark of the Ninja":                    85,
		"Ender Lilies":                         82,
		"Ender Magnolia":                       84,
		"Trine 4":                              80,
		"Trine 5":                              78,
		"Unravel Two":                          77,
		"Gris":                                 84,
		"Neva":                                 83,
		"Fez":                                  88,
		"Braid":                                84,
		"World of Goo":                         82,
		"Donut County":                         78,
		"Sayonara Wild Hearts":                 82,
		"Oxenfree":                             79,
		"Oxenfree II":                          77,
		"Night in the Woods":                   85,
		"Bug Fables":                           86,
		"Chicory: A Colorful Tale":            85,
		"To the Moon":                          80,
		"Finding Paradise":                     72,
		"Impostor Factory":                     76,
		"Omori":                                85,
		"LISA":                                 72,
		"Terraria":                             82,
		"Minecraft":                            86,
		"Minecraft Dungeons":                   72,
		"Dicey Dungeons":                       83,
		"Loop Hero":                            82,
		"Inscryption":                          84,
		"Dredge":                               80,
		"Dave the Diver":                       86,
		"Cocoon":                               88,
		"Bomb Rush Cyberfunk":                  80,
		"Pizza Tower":                          91,
		"ANIMAL WELL":                          86,
		"Pentiment":                            85,
		"Tchia":                                72,
		"Venba":                                82,
		"Planet of Lana":                       75,
		"Jusant":                               78,
		"Hi-Fi Rush":                           87,
		"Palworld":                             68,
		"Cassette Beasts":                      81,
		"Roots of Pacha":                       77,
		"Core Keeper":                          80,
		"Rune Factory 4 Special":               76,
		"Rune Factory 5":                       65,
		"Story of Seasons: Pioneers":           72,
		"Story of Seasons: Friends of Mineral":  70,
		"Harvest Moon":                          58,
		"My Time at Portia":                    67,
		"My Time at Sandrock":                  73,
		"Cozy Grove":                           72,

		// ═══ Visual Novels / Adventure ═══
		"Ace Attorney":                          82,
		"Danganronpa":                           80,
		"AI: The Somnium Files":                 83,
		"AI: The Somnium Files nirvanA":         85,
		"Zero Escape":                           80,
		"Steins;Gate Elite":                     84,
		"Steins;Gate 0":                         79,
		"Chaos;Head Noah":                       72,
		"Clannad":                               81,
		"Little Busters":                        77,
		"The House in Fata Morgana":             95,
		"Witch on the Holy Night":               82,
		"Tsukihime":                             87,
		"Fate/Stay Night":                       87,
		"Raging Loop":                           78,
		"Gnosia":                                79,
		"Famicom Detective Club":                75,
		"Emio The Smiling Man":                  77,
		"Master Detective Archives":             78,

		// ═══ JRPG / Strategy ═══
		"Collection of Mana":                    74,
		"Trials of Mana":                        74,
		"Legend of Mana":                        70,
		"SaGa Frontier":                         71,
		"Romancing SaGa 2":                      81,
		"Romancing SaGa 3":                      78,
		"SaGa Emerald Beyond":                    70,
		"Star Ocean: First Departure R":         74,
		"Star Ocean: The Second Story R":        85,
		"Grandia HD Collection":                 73,
		"Valkyria Chronicles 4":                 82,
		"Valkyria Chronicles":                   80,
		"Ys VIII: Lacrimosa of Dana":            81,
		"Ys IX: Monstrum Nox":                   74,
		"Ys X: Nordics":                         77,
		"Trails of Cold Steel III":              82,
		"Trails of Cold Steel IV":               80,
		"Trails from Zero":                      82,
		"Trails to Azure":                       86,
		"Trails through Daybreak":               82,
		"Disgaea 5 Complete":                    80,
		"Disgaea 6":                             65,
		"Disgaea 7":                             75,
		"Etrian Odyssey Origins":                75,
		"Persona 4 Arena Ultimax":               76,
		"Dragon's Dogma: Dark Arisen":           74,
		"Oninaki":                               66,
		"I Am Setsuna":                          73,
		"Lost Sphear":                           63,
		"The World Ends with You":               82,
		"NEO: The World Ends with You":          83,
		"SMT V: Vengeance":                      85,
		"Astria Ascending":                      66,

		// ═══ Puzzle / Casual ═══
		"Tetris Effect: Connected":              93,
		"Tetris 99":                             80,
		"Lumines Remastered":                    82,
		"Pac-Man 99":                            75,
		"Panel de Pon":                          88,
		"Picross S":                             80,
		"Picross 3D":                            80,
		"Murder by Numbers":                     76,
		"Baba Is You":                           83,
		"Patrick's Parabox":                     85,
		"Portal: Companion Collection":          93,
		"Portal Knights":                        65,
		"The Talos Principle":                   83,
		"The Talos Principle 2":                 82,
		"Human: Fall Flat":                      68,
		"Goodbye Deponia":                       71,
		"Deponia Doomsday":                      68,
		"Edna & Harvey":                          66,
		"Thimbleweed Park":                      82,
		"Spaceplan":                             81,
		"Universal Paperclips":                  83,
		"Duck Simulator":                        66,
	}
}
