import type { CatalogLocalizations } from "./catalogService.js";

function zh(title: string, description: string | null = null): CatalogLocalizations {
  return {
    zhHans: {
      title,
      description
    }
  };
}

export const CATALOG_LOCALIZATION_OVERRIDES: Record<string, CatalogLocalizations> = {
  "the-legend-of-zelda-tears-of-the-kingdom-switch": zh(
    "塞尔达传说 王国之泪",
    "在广阔的海拉鲁大地与天空群岛之间自由冒险，活用全新能力探索、建造与战斗，揭开王国异变背后的真相。"
  ),
  "the-legend-of-zelda-link-s-awakening-switch": zh(
    "塞尔达传说 织梦岛",
    "林克漂流到神秘的可湖霖岛，在可爱又奇幻的世界里收集八件乐器，寻找离开岛屿的方法。"
  ),
  "the-legend-of-zelda-skyward-sword-hd-switch": zh(
    "塞尔达传说 御天之剑 HD",
    "回到塞尔达传说时间轴的起点，使用全新操作方式与更流畅的游玩体验，展开天空与大地之间的冒险。"
  ),
  "the-legend-of-zelda-echoes-of-wisdom-switch": zh(
    "塞尔达传说 智慧的再现",
    "这一次由塞尔达公主踏上旅程，借助复制与组合“回响”的力量，拯救被异变吞噬的海拉鲁。"
  ),
  "hyrule-warriors-definitive-edition-switch": zh(
    "塞尔达无双 海拉鲁全明星 DX",
    "收录《塞尔达传说》系列多位角色的爽快动作作品，在海拉鲁大陆上以无双式战斗横扫大军，并串联起多个经典世界观。"
  ),
  "hyrule-warriors-age-of-calamity-switch": zh(
    "塞尔达无双 灾厄启示录",
    "回到《塞尔达传说 旷野之息》一百年前的灾厄时代，操控英杰与林克并肩作战，亲历大战爆发前后的关键时刻。"
  ),
  "cadence-of-hyrule-switch": zh(
    "凯登丝勇闯海拉鲁",
    "在节奏驱动的地牢冒险中踏入海拉鲁，跟随音乐节拍移动、战斗与探索，与林克和塞尔达一起阻止邪恶势力。"
  ),
  "super-mario-bros-wonder-switch": zh(
    "超级玛利欧兄弟 惊奇",
    "在花花王国展开横向卷轴新冒险，惊奇花会让关卡发生不可思议的变化，带来充满变化的全新游玩体验。"
  ),
  "super-mario-3d-all-stars-switch": zh(
    "超级玛利欧 3D 收藏辑",
    "一次收录《超级玛利欧64》《超级玛利欧阳光》和《超级玛利欧银河》三款 3D 名作，回顾玛利欧立体冒险的经典旅程。"
  ),
  "new-super-mario-bros-u-deluxe-switch": zh(
    "New 超级玛利欧兄弟 U 豪华版",
    "把《New 超级玛利欧兄弟 U》与《New 超级路易吉 U》合并收录，支持多人同乐，以传统横向卷轴关卡展开热闹冒险。"
  ),
  "super-mario-maker-2-switch": zh(
    "超级玛利欧创作家 2",
    "亲手设计属于自己的玛利欧关卡，并游玩来自全球玩家的创意作品，体验创作与闯关结合的高自由度玩法。"
  ),
  "paper-mario-the-origami-king-switch": zh(
    "纸片玛利欧 折纸国王",
    "和伙伴一起踏上纸片风格的冒险，解开折纸王国的谜团，在独特的回合制环形战斗中拯救世界。"
  ),
  "paper-mario-the-thousand-year-door-switch": zh(
    "纸片玛利欧 RPG",
    "在焕然一新的画面下重温千年之门的冒险，和个性十足的伙伴们一起寻找宝藏，揭开古老城市的秘密。"
  ),
  "princess-peach-showtime-switch": zh(
    "碧姬公主 表演时刻！",
    "碧姬公主在舞台剧世界中变换不同职业形态，以剑士、侦探、甜点师等姿态解决各式各样的事件。"
  ),
  "captain-toad-treasure-tracker-switch": zh(
    "前进！奇诺比奥队长",
    "操控不能跳跃的奇诺比奥队长穿梭立体箱庭关卡，旋转场景、寻找宝石与隐藏路线，破解轻巧有趣的机关谜题。"
  ),
  "super-mario-party-switch": zh("超级玛利欧派对"),
  "mario-party-superstars-switch": zh("玛利欧派对 超级巨星"),
  "mario-tennis-aces-switch": zh("玛利欧网球 王牌高手"),
  "mario-golf-super-rush-switch": zh("玛利欧高尔夫 超级冲冲冲"),
  "mario-strikers-battle-league-switch": zh("玛利欧激战前锋 战斗联赛"),
  "donkey-kong-country-tropical-freeze-switch": zh("咚奇刚 热带寒流"),
  "yoshi-s-crafted-world-switch": zh("耀西的手工世界"),
  "kirby-star-allies-switch": zh("星之卡比 新星同盟"),
  "kirby-s-return-to-dream-land-deluxe-switch": zh("星之卡比 Wii 豪华版"),
  "super-smash-bros-ultimate-switch": zh("任天堂明星大乱斗 特别版"),
  "splatoon-2-switch": zh("斯普拉遁2"),
  "nintendo-switch-sports-switch": zh("Nintendo Switch 运动"),
  "ring-fit-adventure-switch": zh("健身环大冒险"),
  "1-2-switch-switch": zh("1-2-Switch"),
  "everybody-1-2-switch-switch": zh("大家的1-2-Switch！"),
  "arms-switch": zh("ARMS"),
  "clubhouse-games-51-worldwide-classics-switch": zh("世界游戏大全 51"),
  "big-brain-academy-brain-vs-brain-switch": zh("脑力锻炼学院 脑力大战"),
  "game-builder-garage-switch": zh("附带导航！一做就上手 第一次的游戏程序设计"),
  "pikmin-1-switch": zh("皮克敏 1"),
  "pikmin-2-switch": zh("皮克敏 2"),
  "pikmin-3-deluxe-switch": zh("皮克敏 3 豪华版"),
  "metroid-prime-remastered-switch": zh("密特罗德 Prime 复刻版"),
  "advance-wars-1-2-re-boot-camp-switch": zh("高级战争 1+2：Re-Boot Camp"),
  "fire-emblem-three-houses-switch": zh("Fire Emblem 风花雪月"),
  "fire-emblem-warriors-switch": zh("Fire Emblem 无双"),
  "fire-emblem-warriors-three-hopes-switch": zh("Fire Emblem 无双 风花雪月"),
  "fire-emblem-engage-switch": zh("Fire Emblem Engage"),
  "xenoblade-chronicles-definitive-edition-switch": zh("异度神剑 终极版"),
  "xenoblade-chronicles-2-switch": zh("异度神剑 2"),
  "xenoblade-chronicles-2-torna-the-golden-country-switch": zh("异度神剑 2 黄金之国伊拉"),
  "xenoblade-chronicles-3-switch": zh("异度神剑 3"),
  "detective-pikachu-returns-switch": zh("名侦探皮卡丘 闪电回归"),
  "new-pokemon-snap-switch": zh("New 宝可梦随乐拍"),
  "pokemon-legends-arceus-switch": zh("宝可梦传说 阿尔宙斯"),
  "pokemon-scarlet-switch": zh("宝可梦 朱"),
  "pokemon-violet-switch": zh("宝可梦 紫"),
  "warioware-get-it-together-switch": zh("分享同乐！瓦力欧制造"),
  "warioware-move-it-switch": zh("超舞动 瓦力欧制造"),
  "bayonetta-switch": zh("猎天使魔女"),
  "bayonetta-2-switch": zh("猎天使魔女 2"),
  "bayonetta-3-switch": zh("猎天使魔女 3"),
  "bayonetta-origins-cereza-and-the-lost-demon-switch": zh("猎天使魔女 起源：瑟蕾莎与迷失的恶魔"),
  "astral-chain-switch": zh("异界锁链"),
  "marvel-ultimate-alliance-3-the-black-order-switch": zh("漫威终极联盟3：黑暗教团"),
  "tokyo-mirage-sessions-fe-encore-switch": zh("幻影异闻录#FE Encore"),
  "famicom-detective-club-the-missing-heir-switch": zh("Famicom侦探俱乐部 消失的继承人"),
  "famicom-detective-club-the-girl-who-stands-behind-switch": zh("Famicom侦探俱乐部 站在身后的少女"),
  "emio-the-smiling-man-famicom-detective-club-switch": zh("笑脸男 EMIO"),
  "another-code-recollection-switch": zh("Another Code 回忆录"),
  "pokken-tournament-dx-switch": zh("宝可拳 DX"),
  "pokemon-mystery-dungeon-rescue-team-dx-switch": zh("宝可梦不可思议迷宫 救助队 DX"),
  "pokemon-let-s-go-pikachu-switch": zh("宝可梦 Let's Go！皮卡丘"),
  "pokemon-let-s-go-eevee-switch": zh("宝可梦 Let's Go！伊布"),
  "pokemon-sword-switch": zh("宝可梦 剑"),
  "pokemon-shield-switch": zh("宝可梦 盾"),
  "pokemon-brilliant-diamond-switch": zh("宝可梦 晶灿钻石"),
  "pokemon-shining-pearl-switch": zh("宝可梦 明亮珍珠"),
  "miitopia-switch": zh("迷托邦"),
  "snipperclips-plus-switch": zh("你裁我剪！斯尼帕 Plus"),
  "good-job-switch": zh("Good Job！"),
  "part-time-ufo-switch": zh("Part Time UFO"),
  "hades-switch": zh("黑帝斯"),
  "celeste-switch": zh("蔚蓝"),
  "stardew-valley-switch": zh("星露谷物语"),
  "shovel-knight-treasure-trove-switch": zh("铲子骑士：无主珍宝"),
  "cuphead-switch": zh("茶杯头"),
  "ori-and-the-blind-forest-definitive-edition-switch": zh("奥日与黑暗森林：终极版"),
  "ori-and-the-will-of-the-wisps-switch": zh("奥日与鬼火意志"),
  "undertale-switch": zh("传说之下"),
  "deltarune-switch": zh("三角符文"),
  "disco-elysium-the-final-cut-switch": zh("极乐迪斯科：最终剪辑版"),
  "slay-the-spire-switch": zh("杀戮尖塔"),
  "into-the-breach-switch": zh("陷阵之志"),
  "the-binding-of-isaac-repentance-switch": zh("以撒的结合：忏悔"),
  "spelunky-2-switch": zh("洞窟探险2"),
  "a-short-hike-switch": zh("短途旅行"),
  "tunic-switch": zh("TUNIC"),
  "sea-of-stars-switch": zh("星之海"),
  "dave-the-diver-switch": zh("潜水员戴夫"),
  "vampire-survivors-switch": zh("吸血鬼幸存者"),
  "balatro-switch": zh("小丑牌"),
  "brotato-switch": zh("土豆兄弟"),
  "ender-lilies-quietus-of-the-knights-switch": zh("终焉莉莉：骑士寂夜"),
  "eastward-switch": zh("风来之国"),
  "katana-zero-switch": zh("武士 零"),
  "hyper-light-drifter-special-edition-switch": zh("光明旅者 特别版"),
  "enter-the-gungeon-switch": zh("挺进地牢"),
  "exit-the-gungeon-switch": zh("逃出地牢"),
  "rogue-legacy-2-switch": zh("盗贼遗产2"),
  "risk-of-rain-returns-switch": zh("雨中冒险：回归"),
  "risk-of-rain-2-switch": zh("雨中冒险2"),
  "axiom-verge-switch": zh("公理边缘"),
  "blasphemous-switch": zh("渎神"),
  "blasphemous-2-switch": zh("渎神2"),
  "monster-sanctuary-switch": zh("怪物圣所"),
  "steamworld-dig-switch": zh("蒸汽世界：挖掘"),
  "steamworld-dig-2-switch": zh("蒸汽世界：挖掘2"),
  "steamworld-heist-switch": zh("蒸汽世界：大劫掠"),
  "steamworld-quest-hand-of-gilgamech-switch": zh("蒸汽世界：探索"),
  "guacamelee-super-turbo-championship-edition-switch": zh("墨西哥英雄大混战！超级涡轮冠军版"),
  "guacamelee-2-switch": zh("墨西哥英雄大混战！2"),
  "the-messenger-switch": zh("信使"),
  "yoku-s-island-express-switch": zh("尤库的小岛速递"),
  "monster-boy-and-the-cursed-kingdom-switch": zh("怪物男孩与被诅咒的王国"),
  "child-of-light-ultimate-edition-switch": zh("光之子：终极版"),
  "bastion-switch": zh("堡垒"),
  "transistor-switch": zh("晶体管"),
  "spiritfarer-switch": zh("灵魂旅人"),
  "gris-switch": zh("GRIS"),
  "oxenfree-switch": zh("狼奔豕突"),
  "oxenfree-ii-lost-signals-switch": zh("狼奔豕突2：失落信号"),
  "kentucky-route-zero-tv-edition-switch": zh("肯塔基零号公路 TV版"),
  "night-in-the-woods-switch": zh("林中之夜"),
  "return-of-the-obra-dinn-switch": zh("奥伯拉丁的回归"),
  "citizen-sleeper-switch": zh("公民沉睡者"),
  "unpacking-switch": zh("拆箱"),
  "phoenix-wright-ace-attorney-trilogy-switch": zh("逆转裁判123 成步堂精选集"),
  "the-great-ace-attorney-chronicles-switch": zh("大逆转裁判 编年史"),
  "apollo-justice-ace-attorney-trilogy-switch": zh("逆转裁判456 王泥喜精选集"),
  "ghost-trick-phantom-detective-switch": zh("幽灵诡计：幻影侦探"),
  "13-sentinels-aegis-rim-switch": zh("十三机兵防卫圈"),
  "persona-5-royal-switch": zh("女神异闻录5 皇家版"),
  "persona-4-golden-switch": zh("女神异闻录4 黄金版"),
  "persona-3-portable-switch": zh("女神异闻录3 携带版"),
  "persona-5-strikers-switch": zh("女神异闻录5 乱战：魅影攻手"),
  "shin-megami-tensei-v-vengeance-switch": zh("真·女神转生V Vengeance"),
  "shin-megami-tensei-iii-nocturne-hd-remaster-switch": zh("真·女神转生III NOCTURNE HD REMASTER"),
  "catherine-full-body-switch": zh("凯瑟琳 Full Body"),
  "dragon-quest-xi-s-echoes-of-an-elusive-age-definitive-edition-switch": zh("勇者斗恶龙XI S 寻觅逝去的时光"),
  "dragon-quest-builders-switch": zh("勇者斗恶龙 创世小玩家 阿雷夫加尔德复兴记"),
  "dragon-quest-builders-2-switch": zh("勇者斗恶龙 创世小玩家2 破坏神席德与空荡岛"),
  "dragon-quest-monsters-the-dark-prince-switch": zh("勇者斗恶龙怪兽仙境3 魔族王子与艾尔芙的旅程"),
  "octopath-traveler-switch": zh("歧路旅人"),
  "octopath-traveler-ii-switch": zh("歧路旅人II"),
  "triangle-strategy-switch": zh("三角战略"),
  "live-a-live-switch": zh("LIVE A LIVE"),
  "chrono-cross-the-radical-dreamers-edition-switch": zh("时空之轮 次元之旅 The Radical Dreamers Edition"),
  "bravely-default-ii-switch": zh("勇气默示录II"),
  "collection-of-mana-switch": zh("圣剑传说 合集"),
  "trials-of-mana-switch": zh("圣剑传说3 TRIALS of MANA"),
  "legend-of-mana-switch": zh("圣剑传说 Legend of Mana"),
  "star-ocean-the-second-story-r-switch": zh("星际海洋 第二个故事 R"),
  "tactics-ogre-reborn-switch": zh("皇家骑士团：重生"),
  "harvestella-switch": zh("丰饶之星"),
  "rune-factory-4-special-switch": zh("符文工房4 特别版"),
  "rune-factory-5-switch": zh("符文工房5"),
  "story-of-seasons-friends-of-mineral-town-switch": zh("牧场物语 重聚矿石镇"),
  "story-of-seasons-a-wonderful-life-switch": zh("牧场物语 Welcome！美丽人生"),
  "story-of-seasons-pioneers-of-olive-town-switch": zh("牧场物语 橄榄镇与希望的大地"),
  "atelier-ryza-ever-darkness-and-the-secret-hideout-switch": zh("莱莎的炼金工房 ～常暗女王与秘密藏身处～"),
  "atelier-ryza-2-lost-legends-and-the-secret-fairy-switch": zh("莱莎的炼金工房2 ～失落传说与秘密妖精～"),
  "atelier-ryza-3-alchemist-of-the-end-and-the-secret-key-switch": zh("莱莎的炼金工房3 ～终结之炼金术士与秘密钥匙～"),
  "unicorn-overlord-switch": zh("圣兽之王"),
  "chained-echoes-switch": zh("连锁回声"),
  "the-elder-scrolls-v-skyrim-switch": zh("上古卷轴V：天际"),
  "the-witcher-3-wild-hunt-complete-edition-switch": zh("巫师3：狂猎 完全版"),
  "diablo-iii-eternal-collection-switch": zh("暗黑破坏神III 永恒收藏版"),
  "diablo-ii-resurrected-switch": zh("暗黑破坏神II 狱火重生"),
  "divinity-original-sin-2-definitive-edition-switch": zh("神界：原罪2 决定版"),
  "sid-meier-s-civilization-vi-switch": zh("席德·梅尔的文明VI"),
  "xcom-2-collection-switch": zh("XCOM 2 收藏辑"),
  "doom-switch": zh("DOOM"),
  "doom-eternal-switch": zh("DOOM Eternal"),
  "wolfenstein-ii-the-new-colossus-switch": zh("德军总部II：新巨像"),
  "bioshock-the-collection-switch": zh("生化奇兵：合集"),
  "borderlands-legendary-collection-switch": zh("无主之地 传奇合集"),
  "portal-companion-collection-switch": zh("传送门：同伴合集"),
  "dying-light-platinum-edition-switch": zh("消逝的光芒 白金版"),
  "no-man-s-sky-switch": zh("无人深空"),
  "subnautica-switch": zh("深海迷航"),
  "subnautica-below-zero-switch": zh("深海迷航：零度之下"),
  "alien-isolation-switch": zh("异形：隔离"),
  "dark-souls-remastered-switch": zh("黑暗之魂：重制版"),
  "darkest-dungeon-switch": zh("暗黑地牢"),
  "monster-hunter-rise-switch": zh("怪物猎人 崛起"),
  "monster-hunter-generations-ultimate-switch": zh("怪物猎人GU"),
  "monster-hunter-stories-2-wings-of-ruin-switch": zh("怪物猎人物语2：破灭之翼"),
  "monster-hunter-stories-switch": zh("怪物猎人物语"),
  "resident-evil-4-switch": zh("生化危机4"),
  "resident-evil-5-switch": zh("生化危机5"),
  "resident-evil-6-switch": zh("生化危机6"),
  "resident-evil-revelations-collection-switch": zh("生化危机 启示录 收藏辑"),
  "resident-evil-0-switch": zh("生化危机0"),
  "resident-evil-switch": zh("生化危机"),
  "devil-may-cry-3-special-edition-switch": zh("鬼泣3 特别版"),
  "dragon-s-dogma-dark-arisen-switch": zh("龙之信条：黑暗觉者"),
  "okami-hd-switch": zh("大神 绝景版"),
  "mega-man-11-switch": zh("洛克人11 命运的齿轮！！"),
  "mega-man-legacy-collection-switch": zh("洛克人 经典合集"),
  "mega-man-x-legacy-collection-switch": zh("洛克人X 传奇合集"),
  "mega-man-zero-zx-legacy-collection-switch": zh("洛克人Zero/ZX 传奇合集"),
  "prince-of-persia-the-lost-crown-switch": zh("波斯王子：失落的王冠"),
  "rayman-legends-definitive-edition-switch": zh("雷曼：传奇 决定版"),
  "crash-bandicoot-n-sane-trilogy-switch": zh("古惑狼 疯狂三部曲"),
  "crash-bandicoot-4-it-s-about-time-switch": zh("古惑狼4：时机已到"),
  "spyro-reignited-trilogy-switch": zh("小龙斯派罗：重燃三部曲"),
  "tony-hawk-s-pro-skater-1-2-switch": zh("托尼·霍克职业滑板 1+2"),
  "burnout-paradise-remastered-switch": zh("火爆狂飙 天堂 复刻版"),
  "grid-autosport-switch": zh("GRID Autosport"),
  "need-for-speed-hot-pursuit-remastered-switch": zh("极品飞车：热力追踪 重制版"),
  "hotshot-racing-switch": zh("Hotshot Racing"),
  "wreckfest-switch": zh("撞车嘉年华"),
  "sonic-mania-switch": zh("索尼克 狂欢"),
  "sonic-origins-switch": zh("索尼克 起源"),
  "sonic-frontiers-switch": zh("索尼克 未知边境"),
  "sonic-superstars-switch": zh("索尼克 超级巨星"),
  "lego-star-wars-the-skywalker-saga-switch": zh("乐高 星球大战：天行者传奇"),
  "lego-city-undercover-switch": zh("乐高都市：卧底风云"),
  "teenage-mutant-ninja-turtles-shredder-s-revenge-switch": zh("忍者神龟：施莱德的复仇"),
  "streets-of-rage-4-switch": zh("怒之铁拳4"),
  "scott-pilgrim-vs-the-world-the-game-switch": zh("歪小子斯科特对抗全世界：游戏"),
  "river-city-girls-switch": zh("热血硬派国夫君外传 热血少女"),
  "river-city-girls-2-switch": zh("热血硬派国夫君外传 热血少女2"),
  "broforce-switch": zh("Broforce"),
  "cult-of-the-lamb-switch": zh("咩咩启示录"),
  "terraria-switch": zh("泰拉瑞亚"),
  "minecraft-switch": zh("我的世界"),
  "minecraft-dungeons-switch": zh("我的世界：地下城"),
  "among-us-switch": zh("Among Us"),
  "fall-guys-switch": zh("糖豆人"),
  "rocket-league-switch": zh("火箭联盟"),
  "fortnite-switch": zh("堡垒之夜"),
  "overwatch-2-switch": zh("守望先锋2"),
  "apex-legends-switch": zh("Apex 英雄"),
  "warframe-switch": zh("星际战甲"),
  "brawlhalla-switch": zh("英灵乱战"),
  "disney-dreamlight-valley-switch": zh("迪士尼 梦幻星谷"),
  "powerwash-simulator-switch": zh("高压水枪模拟器"),
  "dorfromantik-switch": zh("多洛可小镇"),
  "two-point-hospital-jumbo-edition-switch": zh("双点医院 JUMBO版"),
  "two-point-campus-switch": zh("双点校园"),
  "cities-skylines-nintendo-switch-edition-switch": zh("城市：天际线 Nintendo Switch版"),
  "pico-park-switch": zh("PICO PARK"),
  "human-fall-flat-switch": zh("人类：一败涂地"),
  "overcooked-special-edition-switch": zh("胡闹厨房 特别版"),
  "overcooked-2-switch": zh("胡闹厨房2"),
  "moving-out-switch": zh("胡闹搬家"),
  "moving-out-2-switch": zh("胡闹搬家2"),
  "tools-up-switch": zh("Tools Up!"),
  "lovers-in-a-dangerous-spacetime-switch": zh("危险时空的恋人"),
  "it-takes-two-switch": zh("双人成行"),
  "unravel-two-switch": zh("毛线小精灵2"),
  "boomerang-fu-switch": zh("回旋镖大乱斗"),
  "heave-ho-switch": zh("Heave Ho"),
  "untitled-goose-game-switch": zh("鹅作剧"),
  "goat-simulator-the-goaty-switch": zh("模拟山羊 GOATY版"),
  "katamari-damacy-reroll-switch": zh("块魂 安可"),
  "we-love-katamari-reroll-royal-reverie-switch": zh("我们喜欢块魂 安可+ 国王大人的小小回忆"),
  "taiko-no-tatsujin-drum-n-fun-switch": zh("太鼓之达人 Nintendo Switch版！"),
  "taiko-no-tatsujin-rhythm-festival-switch": zh("太鼓之达人 咚咚雷音祭"),
  "muse-dash-switch": zh("喵斯快跑"),
  "groove-coaster-wai-wai-party-switch": zh("炫音轨迹 Wai Wai Party!!!!"),
  "crypt-of-the-necrodancer-switch": zh("节奏地牢"),
  "tetris-effect-connected-switch": zh("俄罗斯方块效应：连接"),
  "puyo-puyo-tetris-switch": zh("魔法气泡 俄罗斯方块"),
  "lumines-remastered-switch": zh("Lumines Remastered"),
  "fitness-boxing-switch": zh("有氧拳击"),
  "fitness-boxing-2-rhythm-and-exercise-switch": zh("有氧拳击2：节奏与运动"),
  "fitness-boxing-fist-of-the-north-star-switch": zh("Fitness Boxing 北斗神拳"),
  "samba-de-amigo-party-central-switch": zh("Samba de Amigo：摇摇乐派对"),
  "deemo-switch": zh("DEEMO"),
  "voez-switch": zh("VOEZ"),
  "hatsune-miku-project-diva-mega-mix-switch": zh("初音未来 Project DIVA MEGA39's"),
  "ys-viii-lacrimosa-of-dana-switch": zh("伊苏VIII -丹娜的陨涕日-"),
  "ys-ix-monstrum-nox-switch": zh("伊苏IX -怪人之夜-"),
  "ys-x-nordics-switch": zh("伊苏X -北境历险-"),
  "the-legend-of-heroes-trails-from-zero-switch": zh("英雄传说 零之轨迹"),
  "the-legend-of-heroes-trails-to-azure-switch": zh("英雄传说 碧之轨迹"),
  "the-legend-of-heroes-trails-into-reverie-switch": zh("英雄传说 创之轨迹"),
  "the-legend-of-heroes-trails-of-cold-steel-iii-switch": zh("英雄传说 闪之轨迹III"),
  "the-legend-of-heroes-trails-of-cold-steel-iv-switch": zh("英雄传说 闪之轨迹IV"),
  "disgaea-5-complete-switch": zh("魔界战记5 完全版")
};
