export interface ExtendedCatalogSeedData {
  externalId: string;
  title: string;
  fallbackPriceAmount: number | null;
}

const RAW_EXTENDED_CATALOG_SEEDS = [
  "the-legend-of-zelda-tears-of-the-kingdom-switch|The Legend of Zelda: Tears of the Kingdom|59.99",
  "the-legend-of-zelda-link-s-awakening-switch|The Legend of Zelda: Link's Awakening|59.99",
  "the-legend-of-zelda-skyward-sword-hd-switch|The Legend of Zelda: Skyward Sword HD|59.99",
  "the-legend-of-zelda-echoes-of-wisdom-switch|The Legend of Zelda: Echoes of Wisdom|59.99",
  "hyrule-warriors-definitive-edition-switch|Hyrule Warriors: Definitive Edition|59.99",
  "hyrule-warriors-age-of-calamity-switch|Hyrule Warriors: Age of Calamity|59.99",
  "cadence-of-hyrule-switch|Cadence of Hyrule|59.99",
  "super-mario-bros-wonder-switch|Super Mario Bros. Wonder|59.99",
  "super-mario-3d-all-stars-switch|Super Mario 3D All-Stars|59.99",
  "new-super-mario-bros-u-deluxe-switch|New Super Mario Bros. U Deluxe|59.99",
  "super-mario-maker-2-switch|Super Mario Maker 2|59.99",
  "paper-mario-the-origami-king-switch|Paper Mario: The Origami King|59.99",
  "paper-mario-the-thousand-year-door-switch|Paper Mario: The Thousand-Year Door|59.99",
  "princess-peach-showtime-switch|Princess Peach: Showtime!|59.99",
  "captain-toad-treasure-tracker-switch|Captain Toad: Treasure Tracker|59.99",
  "super-mario-party-switch|Super Mario Party|59.99",
  "mario-party-superstars-switch|Mario Party Superstars|59.99",
  "mario-tennis-aces-switch|Mario Tennis Aces|59.99",
  "mario-golf-super-rush-switch|Mario Golf: Super Rush|59.99",
  "mario-strikers-battle-league-switch|Mario Strikers: Battle League|59.99",
  "donkey-kong-country-tropical-freeze-switch|Donkey Kong Country: Tropical Freeze|59.99",
  "yoshi-s-crafted-world-switch|Yoshi's Crafted World|59.99",
  "kirby-star-allies-switch|Kirby Star Allies|59.99",
  "kirby-s-return-to-dream-land-deluxe-switch|Kirby's Return to Dream Land Deluxe|59.99",
  "super-smash-bros-ultimate-switch|Super Smash Bros. Ultimate|59.99",
  "splatoon-2-switch|Splatoon 2|59.99",
  "nintendo-switch-sports-switch|Nintendo Switch Sports|59.99",
  "ring-fit-adventure-switch|Ring Fit Adventure|59.99",
  "1-2-switch-switch|1-2-Switch|59.99",
  "everybody-1-2-switch-switch|Everybody 1-2-Switch!|59.99",
  "arms-switch|ARMS|59.99",
  "clubhouse-games-51-worldwide-classics-switch|Clubhouse Games: 51 Worldwide Classics|59.99",
  "big-brain-academy-brain-vs-brain-switch|Big Brain Academy: Brain vs. Brain|59.99",
  "game-builder-garage-switch|Game Builder Garage|59.99",
  "pikmin-1-switch|Pikmin 1|59.99",
  "pikmin-2-switch|Pikmin 2|59.99",
  "pikmin-3-deluxe-switch|Pikmin 3 Deluxe|59.99",
  "metroid-prime-remastered-switch|Metroid Prime Remastered|59.99",
  "advance-wars-1-2-re-boot-camp-switch|Advance Wars 1+2: Re-Boot Camp|59.99",
  "fire-emblem-three-houses-switch|Fire Emblem: Three Houses|59.99",
  "fire-emblem-warriors-switch|Fire Emblem Warriors|59.99",
  "fire-emblem-warriors-three-hopes-switch|Fire Emblem Warriors: Three Hopes|59.99",
  "fire-emblem-engage-switch|Fire Emblem Engage|59.99",
  "xenoblade-chronicles-definitive-edition-switch|Xenoblade Chronicles: Definitive Edition|59.99",
  "xenoblade-chronicles-2-switch|Xenoblade Chronicles 2|59.99",
  "xenoblade-chronicles-2-torna-the-golden-country-switch|Xenoblade Chronicles 2: Torna - The Golden Country|59.99",
  "xenoblade-chronicles-3-switch|Xenoblade Chronicles 3|59.99",
  "bayonetta-switch|Bayonetta|59.99",
  "bayonetta-2-switch|Bayonetta 2|59.99",
  "bayonetta-3-switch|Bayonetta 3|59.99",
  "bayonetta-origins-cereza-and-the-lost-demon-switch|Bayonetta Origins: Cereza and the Lost Demon|59.99",
  "astral-chain-switch|Astral Chain|59.99",
  "marvel-ultimate-alliance-3-the-black-order-switch|Marvel Ultimate Alliance 3: The Black Order|59.99",
  "tokyo-mirage-sessions-fe-encore-switch|Tokyo Mirage Sessions #FE Encore|59.99",
  "famicom-detective-club-the-missing-heir-switch|Famicom Detective Club: The Missing Heir|59.99",
  "famicom-detective-club-the-girl-who-stands-behind-switch|Famicom Detective Club: The Girl Who Stands Behind|59.99",
  "emio-the-smiling-man-famicom-detective-club-switch|Emio - The Smiling Man: Famicom Detective Club|59.99",
  "another-code-recollection-switch|Another Code: Recollection|59.99",
  "detective-pikachu-returns-switch|Detective Pikachu Returns|59.99",
  "new-pokemon-snap-switch|New Pokemon Snap|59.99",
  "pokken-tournament-dx-switch|Pokken Tournament DX|59.99",
  "pokemon-mystery-dungeon-rescue-team-dx-switch|Pokemon Mystery Dungeon: Rescue Team DX|59.99",
  "pokemon-let-s-go-pikachu-switch|Pokemon Let's Go, Pikachu!|59.99",
  "pokemon-let-s-go-eevee-switch|Pokemon Let's Go, Eevee!|59.99",
  "pokemon-sword-switch|Pokemon Sword|59.99",
  "pokemon-shield-switch|Pokemon Shield|59.99",
  "pokemon-brilliant-diamond-switch|Pokemon Brilliant Diamond|59.99",
  "pokemon-shining-pearl-switch|Pokemon Shining Pearl|59.99",
  "pokemon-legends-arceus-switch|Pokemon Legends: Arceus|59.99",
  "pokemon-scarlet-switch|Pokemon Scarlet|59.99",
  "pokemon-violet-switch|Pokemon Violet|59.99",
  "miitopia-switch|Miitopia|59.99",
  "warioware-get-it-together-switch|WarioWare: Get It Together!|59.99",
  "warioware-move-it-switch|WarioWare: Move It!|59.99",
  "snipperclips-plus-switch|Snipperclips Plus|59.99",
  "good-job-switch|Good Job!|59.99",
  "part-time-ufo-switch|Part Time UFO|59.99",
  "hades-switch|Hades|29.99",
  "celeste-switch|Celeste|29.99",
  "stardew-valley-switch|Stardew Valley|29.99",
  "shovel-knight-treasure-trove-switch|Shovel Knight: Treasure Trove|29.99",
  "cuphead-switch|Cuphead|29.99",
  "ori-and-the-blind-forest-definitive-edition-switch|Ori and the Blind Forest: Definitive Edition|29.99",
  "ori-and-the-will-of-the-wisps-switch|Ori and the Will of the Wisps|29.99",
  "undertale-switch|Undertale|29.99",
  "deltarune-switch|Deltarune|29.99",
  "disco-elysium-the-final-cut-switch|Disco Elysium - The Final Cut|29.99",
  "slay-the-spire-switch|Slay the Spire|29.99",
  "into-the-breach-switch|Into the Breach|29.99",
  "the-binding-of-isaac-repentance-switch|The Binding of Isaac: Repentance|29.99",
  "spelunky-2-switch|Spelunky 2|29.99",
  "a-short-hike-switch|A Short Hike|29.99",
  "tunic-switch|Tunic|29.99",
  "sea-of-stars-switch|Sea of Stars|29.99",
  "dave-the-diver-switch|Dave the Diver|29.99",
  "vampire-survivors-switch|Vampire Survivors|29.99",
  "balatro-switch|Balatro|29.99",
  "brotato-switch|Brotato|29.99",
  "ender-lilies-quietus-of-the-knights-switch|Ender Lilies: Quietus of the Knights|29.99",
  "eastward-switch|Eastward|29.99",
  "katana-zero-switch|Katana ZERO|29.99",
  "hyper-light-drifter-special-edition-switch|Hyper Light Drifter: Special Edition|29.99",
  "enter-the-gungeon-switch|Enter the Gungeon|29.99",
  "exit-the-gungeon-switch|Exit the Gungeon|29.99",
  "rogue-legacy-2-switch|Rogue Legacy 2|29.99",
  "risk-of-rain-returns-switch|Risk of Rain Returns|29.99",
  "risk-of-rain-2-switch|Risk of Rain 2|29.99",
  "axiom-verge-switch|Axiom Verge|29.99",
  "blasphemous-switch|Blasphemous|29.99",
  "blasphemous-2-switch|Blasphemous 2|29.99",
  "monster-sanctuary-switch|Monster Sanctuary|29.99",
  "steamworld-dig-switch|SteamWorld Dig|29.99",
  "steamworld-dig-2-switch|SteamWorld Dig 2|29.99",
  "steamworld-heist-switch|SteamWorld Heist|29.99",
  "steamworld-quest-hand-of-gilgamech-switch|SteamWorld Quest: Hand of Gilgamech|29.99",
  "guacamelee-super-turbo-championship-edition-switch|Guacamelee! Super Turbo Championship Edition|29.99",
  "guacamelee-2-switch|Guacamelee! 2|29.99",
  "the-messenger-switch|The Messenger|29.99",
  "yoku-s-island-express-switch|Yoku's Island Express|29.99",
  "monster-boy-and-the-cursed-kingdom-switch|Monster Boy and the Cursed Kingdom|29.99",
  "child-of-light-ultimate-edition-switch|Child of Light: Ultimate Edition|29.99",
  "bastion-switch|Bastion|29.99",
  "transistor-switch|Transistor|29.99",
  "spiritfarer-switch|Spiritfarer|29.99",
  "gris-switch|GRIS|29.99",
  "oxenfree-switch|Oxenfree|29.99",
  "oxenfree-ii-lost-signals-switch|Oxenfree II: Lost Signals|29.99",
  "kentucky-route-zero-tv-edition-switch|Kentucky Route Zero: TV Edition|29.99",
  "night-in-the-woods-switch|Night in the Woods|29.99",
  "return-of-the-obra-dinn-switch|Return of the Obra Dinn|29.99",
  "citizen-sleeper-switch|Citizen Sleeper|29.99",
  "unpacking-switch|Unpacking|29.99",
  "phoenix-wright-ace-attorney-trilogy-switch|Phoenix Wright: Ace Attorney Trilogy|29.99",
  "the-great-ace-attorney-chronicles-switch|The Great Ace Attorney Chronicles|29.99",
  "apollo-justice-ace-attorney-trilogy-switch|Apollo Justice: Ace Attorney Trilogy|29.99",
  "ghost-trick-phantom-detective-switch|Ghost Trick: Phantom Detective|29.99",
  "13-sentinels-aegis-rim-switch|13 Sentinels: Aegis Rim|29.99",
  "persona-5-royal-switch|Persona 5 Royal|29.99",
  "persona-4-golden-switch|Persona 4 Golden|29.99",
  "persona-3-portable-switch|Persona 3 Portable|29.99",
  "persona-5-strikers-switch|Persona 5 Strikers|29.99",
  "shin-megami-tensei-v-vengeance-switch|Shin Megami Tensei V: Vengeance|29.99",
  "shin-megami-tensei-iii-nocturne-hd-remaster-switch|Shin Megami Tensei III Nocturne HD Remaster|29.99",
  "catherine-full-body-switch|Catherine: Full Body|29.99",
  "dragon-quest-xi-s-echoes-of-an-elusive-age-definitive-edition-switch|Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition|29.99",
  "dragon-quest-builders-switch|Dragon Quest Builders|29.99",
  "dragon-quest-builders-2-switch|Dragon Quest Builders 2|29.99",
  "dragon-quest-monsters-the-dark-prince-switch|Dragon Quest Monsters: The Dark Prince|29.99",
  "octopath-traveler-switch|Octopath Traveler|29.99",
  "octopath-traveler-ii-switch|Octopath Traveler II|29.99",
  "triangle-strategy-switch|Triangle Strategy|29.99",
  "live-a-live-switch|Live A Live|29.99",
  "chrono-cross-the-radical-dreamers-edition-switch|Chrono Cross: The Radical Dreamers Edition|29.99",
  "bravely-default-ii-switch|Bravely Default II|29.99",
  "collection-of-mana-switch|Collection of Mana|29.99",
  "trials-of-mana-switch|Trials of Mana|29.99",
  "legend-of-mana-switch|Legend of Mana|29.99",
  "star-ocean-the-second-story-r-switch|Star Ocean: The Second Story R|29.99",
  "tactics-ogre-reborn-switch|Tactics Ogre: Reborn|29.99",
  "harvestella-switch|Harvestella|29.99",
  "rune-factory-4-special-switch|Rune Factory 4 Special|29.99",
  "rune-factory-5-switch|Rune Factory 5|29.99",
  "story-of-seasons-friends-of-mineral-town-switch|Story of Seasons: Friends of Mineral Town|29.99",
  "story-of-seasons-a-wonderful-life-switch|Story of Seasons: A Wonderful Life|29.99",
  "story-of-seasons-pioneers-of-olive-town-switch|Story of Seasons: Pioneers of Olive Town|29.99",
  "atelier-ryza-ever-darkness-and-the-secret-hideout-switch|Atelier Ryza: Ever Darkness & the Secret Hideout|29.99",
  "atelier-ryza-2-lost-legends-and-the-secret-fairy-switch|Atelier Ryza 2: Lost Legends & the Secret Fairy|29.99",
  "atelier-ryza-3-alchemist-of-the-end-and-the-secret-key-switch|Atelier Ryza 3: Alchemist of the End & the Secret Key|29.99",
  "unicorn-overlord-switch|Unicorn Overlord|29.99",
  "chained-echoes-switch|Chained Echoes|29.99",
  "the-elder-scrolls-v-skyrim-switch|The Elder Scrolls V: Skyrim|29.99",
  "the-witcher-3-wild-hunt-complete-edition-switch|The Witcher 3: Wild Hunt - Complete Edition|29.99",
  "diablo-iii-eternal-collection-switch|Diablo III: Eternal Collection|29.99",
  "diablo-ii-resurrected-switch|Diablo II: Resurrected|29.99",
  "divinity-original-sin-2-definitive-edition-switch|Divinity: Original Sin 2 - Definitive Edition|29.99",
  "sid-meier-s-civilization-vi-switch|Sid Meier's Civilization VI|29.99",
  "xcom-2-collection-switch|XCOM 2 Collection|29.99",
  "doom-switch|DOOM|29.99",
  "doom-eternal-switch|DOOM Eternal|29.99",
  "wolfenstein-ii-the-new-colossus-switch|Wolfenstein II: The New Colossus|29.99",
  "bioshock-the-collection-switch|BioShock: The Collection|29.99",
  "borderlands-legendary-collection-switch|Borderlands Legendary Collection|29.99",
  "portal-companion-collection-switch|Portal: Companion Collection|29.99",
  "dying-light-platinum-edition-switch|Dying Light: Platinum Edition|29.99",
  "no-man-s-sky-switch|No Man's Sky|29.99",
  "subnautica-switch|Subnautica|29.99",
  "subnautica-below-zero-switch|Subnautica: Below Zero|29.99",
  "alien-isolation-switch|Alien: Isolation|29.99",
  "dark-souls-remastered-switch|Dark Souls: Remastered|29.99",
  "darkest-dungeon-switch|Darkest Dungeon|29.99",
  "monster-hunter-rise-switch|Monster Hunter Rise|29.99",
  "monster-hunter-generations-ultimate-switch|Monster Hunter Generations Ultimate|29.99",
  "monster-hunter-stories-2-wings-of-ruin-switch|Monster Hunter Stories 2: Wings of Ruin|29.99",
  "monster-hunter-stories-switch|Monster Hunter Stories|29.99",
  "resident-evil-4-switch|Resident Evil 4|29.99",
  "resident-evil-5-switch|Resident Evil 5|29.99",
  "resident-evil-6-switch|Resident Evil 6|29.99",
  "resident-evil-revelations-collection-switch|Resident Evil Revelations Collection|29.99",
  "resident-evil-0-switch|Resident Evil 0|29.99",
  "resident-evil-switch|Resident Evil|29.99",
  "devil-may-cry-3-special-edition-switch|Devil May Cry 3 Special Edition|29.99",
  "dragon-s-dogma-dark-arisen-switch|Dragon's Dogma: Dark Arisen|29.99",
  "okami-hd-switch|Okami HD|29.99",
  "mega-man-11-switch|Mega Man 11|29.99",
  "mega-man-legacy-collection-switch|Mega Man Legacy Collection|29.99",
  "mega-man-x-legacy-collection-switch|Mega Man X Legacy Collection|29.99",
  "mega-man-zero-zx-legacy-collection-switch|Mega Man Zero/ZX Legacy Collection|29.99",
  "prince-of-persia-the-lost-crown-switch|Prince of Persia: The Lost Crown|29.99",
  "rayman-legends-definitive-edition-switch|Rayman Legends: Definitive Edition|29.99",
  "crash-bandicoot-n-sane-trilogy-switch|Crash Bandicoot N. Sane Trilogy|29.99",
  "crash-bandicoot-4-it-s-about-time-switch|Crash Bandicoot 4: It's About Time|29.99",
  "spyro-reignited-trilogy-switch|Spyro Reignited Trilogy|29.99",
  "tony-hawk-s-pro-skater-1-2-switch|Tony Hawk's Pro Skater 1 + 2|29.99",
  "burnout-paradise-remastered-switch|Burnout Paradise Remastered|29.99",
  "grid-autosport-switch|GRID Autosport|29.99",
  "need-for-speed-hot-pursuit-remastered-switch|Need for Speed Hot Pursuit Remastered|29.99",
  "hotshot-racing-switch|Hotshot Racing|29.99",
  "wreckfest-switch|Wreckfest|29.99",
  "sonic-mania-switch|Sonic Mania|29.99",
  "sonic-origins-switch|Sonic Origins|29.99",
  "sonic-frontiers-switch|Sonic Frontiers|29.99",
  "sonic-superstars-switch|Sonic Superstars|29.99",
  "lego-star-wars-the-skywalker-saga-switch|LEGO Star Wars: The Skywalker Saga|29.99",
  "lego-city-undercover-switch|LEGO City Undercover|29.99",
  "teenage-mutant-ninja-turtles-shredder-s-revenge-switch|Teenage Mutant Ninja Turtles: Shredder's Revenge|29.99",
  "streets-of-rage-4-switch|Streets of Rage 4|29.99",
  "scott-pilgrim-vs-the-world-the-game-switch|Scott Pilgrim vs. The World: The Game|29.99",
  "river-city-girls-switch|River City Girls|29.99",
  "river-city-girls-2-switch|River City Girls 2|29.99",
  "broforce-switch|Broforce|29.99",
  "cult-of-the-lamb-switch|Cult of the Lamb|29.99",
  "terraria-switch|Terraria|29.99",
  "minecraft-switch|Minecraft|29.99",
  "minecraft-dungeons-switch|Minecraft Dungeons|29.99",
  "among-us-switch|Among Us|29.99",
  "fall-guys-switch|Fall Guys|29.99",
  "rocket-league-switch|Rocket League|29.99",
  "fortnite-switch|Fortnite|29.99",
  "overwatch-2-switch|Overwatch 2|29.99",
  "apex-legends-switch|Apex Legends|29.99",
  "warframe-switch|Warframe|29.99",
  "brawlhalla-switch|Brawlhalla|29.99",
  "disney-dreamlight-valley-switch|Disney Dreamlight Valley|29.99",
  "powerwash-simulator-switch|PowerWash Simulator|29.99",
  "dorfromantik-switch|Dorfromantik|29.99",
  "two-point-hospital-jumbo-edition-switch|Two Point Hospital: JUMBO Edition|29.99",
  "two-point-campus-switch|Two Point Campus|29.99",
  "cities-skylines-nintendo-switch-edition-switch|Cities: Skylines - Nintendo Switch Edition|29.99",
  "pico-park-switch|PICO PARK|29.99",
  "human-fall-flat-switch|Human: Fall Flat|29.99",
  "overcooked-special-edition-switch|Overcooked: Special Edition|29.99",
  "overcooked-2-switch|Overcooked! 2|29.99",
  "moving-out-switch|Moving Out|29.99",
  "moving-out-2-switch|Moving Out 2|29.99",
  "tools-up-switch|Tools Up!|29.99",
  "lovers-in-a-dangerous-spacetime-switch|Lovers in a Dangerous Spacetime|29.99",
  "it-takes-two-switch|It Takes Two|29.99",
  "unravel-two-switch|Unravel Two|29.99",
  "boomerang-fu-switch|Boomerang Fu|29.99",
  "heave-ho-switch|Heave Ho|29.99",
  "untitled-goose-game-switch|Untitled Goose Game|29.99",
  "goat-simulator-the-goaty-switch|Goat Simulator: The GOATY|29.99",
  "katamari-damacy-reroll-switch|Katamari Damacy REROLL|29.99",
  "we-love-katamari-reroll-royal-reverie-switch|We Love Katamari REROLL+ Royal Reverie|29.99",
  "taiko-no-tatsujin-drum-n-fun-switch|Taiko no Tatsujin: Drum 'n' Fun!|29.99",
  "taiko-no-tatsujin-rhythm-festival-switch|Taiko no Tatsujin: Rhythm Festival|29.99",
  "muse-dash-switch|Muse Dash|29.99",
  "groove-coaster-wai-wai-party-switch|Groove Coaster Wai Wai Party!!!!|29.99",
  "crypt-of-the-necrodancer-switch|Crypt of the NecroDancer|29.99",
  "tetris-effect-connected-switch|Tetris Effect: Connected|29.99",
  "puyo-puyo-tetris-switch|Puyo Puyo Tetris|29.99",
  "lumines-remastered-switch|Lumines Remastered|29.99",
  "fitness-boxing-switch|Fitness Boxing|29.99",
  "fitness-boxing-2-rhythm-and-exercise-switch|Fitness Boxing 2: Rhythm & Exercise|29.99",
  "fitness-boxing-fist-of-the-north-star-switch|Fitness Boxing Fist of the North Star|29.99",
  "samba-de-amigo-party-central-switch|Samba de Amigo: Party Central|29.99",
  "deemo-switch|DEEMO|29.99",
  "voez-switch|VOEZ|29.99",
  "hatsune-miku-project-diva-mega-mix-switch|Hatsune Miku: Project DIVA Mega Mix|29.99",
  "ys-viii-lacrimosa-of-dana-switch|Ys VIII: Lacrimosa of DANA|29.99",
  "ys-ix-monstrum-nox-switch|Ys IX: Monstrum Nox|29.99",
  "ys-x-nordics-switch|Ys X: Nordics|29.99",
  "the-legend-of-heroes-trails-from-zero-switch|The Legend of Heroes: Trails from Zero|29.99",
  "the-legend-of-heroes-trails-to-azure-switch|The Legend of Heroes: Trails to Azure|29.99",
  "the-legend-of-heroes-trails-into-reverie-switch|The Legend of Heroes: Trails into Reverie|29.99",
  "the-legend-of-heroes-trails-of-cold-steel-iii-switch|The Legend of Heroes: Trails of Cold Steel III|29.99",
  "the-legend-of-heroes-trails-of-cold-steel-iv-switch|The Legend of Heroes: Trails of Cold Steel IV|29.99",
  "disgaea-5-complete-switch|Disgaea 5 Complete|29.99",
];

export const EXTENDED_CATALOG_SEEDS: ExtendedCatalogSeedData[] = RAW_EXTENDED_CATALOG_SEEDS.map((row) => {
  const [externalId, title, price] = row.split("|");
  return {
    externalId,
    title,
    fallbackPriceAmount: price ? Number(price) : null
  };
});
